name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: yarn
      - name: Creates static storybook test site
        run: yarn storybook:build
      - name: Static server for storybook site
        run: node --experimental-json-modules static-storybook-server.mjs &
        env:
          PORT: 6006
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test:unit
      - name: E2E tests
        run: yarn test:e2e-headless
      - name: Build
        run: yarn build
      - name: Size Check
        run: yarn size
      - name: Save built files to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Automated build updated
          file_pattern: dist
